FROM node
MAINTAINER woochul <crepers12@hanmail.net>

WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app
CMD node app.js

EXPOSE 5000

#docker build --tag=node-web
#docker run -p 5000:80 --name node-web node
#open http://localhost:5000 on the browser